### ISSUE TITLE
html mappings in javascript

### ISSUE THREAD

**Issue by tthomas7** [tpope/vim-ragtag#34]
I'm not sure if this is the right place for this, feel free to close it if not. But I've been wanting the <C-X><splace> and <CR> tag mappings in my coffeescript files. I guess I'd like either for them to be available by default or a way to force them regardless of file type. Let me know if I can help or am just being dumb.
Thanks.

**Comment by armacento** [comment]
I too was trying to play around with implementing this feature, by adding an isFiletype('js') call to all lines with html calls, however it didn't work. How can we fix this?

**Comment by tpope** [comment]
Oh, you probably want `g:ragtag_global_maps`.

**Comment by armacento** [comment]
Not sure what you mean, I added ```﻿﻿let g:ragtag_global_maps = 1``` to vimrc and it didn't do anything.

**Comment by tpope** [comment]
It does [several maps](https://github.com/tpope/vim-ragtag/blob/0ef3f6a5778467fbca12b7874a4509593b209228/plugin/ragtag.vim#L555-L562) that I've found generally useful but omits most notably maps that are language specific (e.g. `<C-X>=`). Open to expanding the list if there is something in particular you are missing.

**Comment by armacento** [comment]
Ah okay, I was trying to use the xml/html maps in a .js file.  I'm primarily interested in the convert to tag maps (div<C-X><Space>  ---> <div></div>), since I use html syntax in javascript.

**Comment by tpope** [comment]
I think `<C-X><Space>` would be a good addition to the global maps.

**Comment by armacento** [comment]
I tried adding it with a plug to ragtagHtmlComplete but it didn't do anything. I also barely know my way around vimscript.
