### ISSUE TITLE
Spurious ^F appended to tag completions when in presence of vim-sleuth plugin.

### ISSUE THREAD

**Issue by bluz71** [tpope/vim-ragtag#48]
Hello,

Playing with [vim-sleuth](https://github.com/tpope/vim-sleuth) today and I notice it effects vim-ragtag in a weird way. 

The presence of vim-sleuth somehow results in tag-language completions, via `Control-/`, emitting an extra `^F` character at the end of the completed closing tag. 

Comment out vim-sleuth, no spurious `^F`.

Happens for me on Linux & Mac with both Vim and Neovim via a minimal vimrc.

The issue may be over in vim-sleuth, not here in vim-ragtag. But it seemed more appropriate to report it here.

Many thanks.

**Comment by bluz71** [comment]
Plugin ordering matters. I should have thought of thought initially; anyway I've got interesting results.

This ordering has the `^F` issue:

```
Plug 'tpope/vim-ragtag'
Plug 'tpope/vim-sleuth'
```

This ordering has no issue:

```
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-ragtag'
```

Thanks.

**Comment by tpope** [comment]
So here's what's going on.

* The `'indentkeys'` option, which basically tells Vim when to reindent, defaultings to including `!^F`, which means "when the user presses CTRL-F, discard it and reindent"
* Most filetypes preserve `!^F`, but a few override it. Ragtag re-adds it if it was removed.
* Many Ragtag maps, including `<C-/>`, include `<C-F>` to force reindent.

My guess you're using one of those filetypes that removes `!^F` from `'indentkeys`, and the dependency order affects Ragtag's success at re-adding it. Check `:verbose set indentkeys?` and see if you can find the culprit. After that we can come up with a workaround.

**Comment by bluz71** [comment]
Hello Tim,

Vim `xml` filetype appears to be the only filetype giving grief.

After quite some testing Rails ERB, React JSX, SGML and raw HTML are all good, no extra `^F` no matter the ordering of ragtag and sleuth.

For `xml` filetype these are the `:verbose set indentkeys?` results:

- When sleuth plugin is loaded **before** ragtag plugin (aka the working case):

```
  indentkeys=o,O,*<Return>,<>>,<<>,/,{,},!^F
        Last set from ~/dotfiles/vim/plugged/vim-ragtag/plugin/ragtag.vim
```

- When ragtag plugin is loaded **before** sleuth plugin (aka the case that emits unwanted `^F`):

```
  indentkeys=o,O,*<Return>,<>>,<<>,/,{,}
        Last set from /usr/local/Cellar/vim/8.0.1600/share/vim/vim80/indent/xml.vim
```

- When neither ragtag or sleuth plugins are loaded:

```
  indentkeys=o,O,*<Return>,<>>,<<>,/,{,}
        Last set from /usr/local/Cellar/vim/8.0.1600/share/vim/vim80/indent/xml.vim
```

Interestingly, Vim default `indentkeys` for HTML and SGML does contain `^F`, but not for XML.

Strange one, but quite rare, I doubt many folks are editing raw XML files. From memory I must have been editing a fontconfig `conf` file which is XML.

I don't mind if you close this as too weird, maybe with just a warning in the README about XML and sleuth and a hint to load sleuth before ragtag if folks are using both plugins?

Many thanks.

**Comment by tpope** [comment]
Long story short, I'm going to roll back https://github.com/tpope/vim-sleuth/commit/b6347df73719dea0fb14695eae4d3506ebc4a36c. By forcing `filetype indent on` to happen so late, Ragtag ends up running before the indent plugin, so it can't override `'indentkeys'`.

That commit was a speculative attempt to fix a different load order issue, but I no longer remember the specifics, so for lack of a better option, I'll have to see what if anything breaks once it's gone.
