### ISSUE TITLE
<Link> tag closing `Ctrl-x Ctrl-/` issue

### ISSUE THREAD

**Issue by bluz71** [tpope/vim-ragtag#49]
Hello,

Interesting quirk I notice when using ragtag (for tag-closing) whilst coding up some React (with React-router).

For some reason closing `<Link>` tags does not work, basically the closing tag will be `</>` rather than `</Link>`.

Both words `Link` and `link` are problematic.

I stripped my vimrc right back and the issue remains. Link/link are the only words I've encountered that fail to close via `Ctrl-x Ctrl-/`. Link1, Foobar, Freddy are all fine, but Link seems to be a reserved word. Worth reporting here.

Side note, in React-router `<Link>` is an often used component.

Many thanks, this is an excellent plugin.

**Comment by tpope** [comment]
It skips over self closing tags like `link` and `img`. The idea is that it can automatically insert `</head>` in the following:

```html
<head>
  <link rel="stylesheet" href="/styles.css">
```

Ragtag delegates to the HTML omnicompletion for this, literally calling `</CTRL-X CTRL-O`, so if you are looking for a configuration option or workaround, check there.
