### ISSUE TITLE
Increase wait time between key presses to complete a sequence

### ISSUE THREAD

**Issue by mrzool** [tpope/vim-ragtag#50]
I’d like to *slightly* increase the grace time between hitting a chord (say `<C-X>`) and the subsequent key press that completes the sequence. Tried increasing `ttimeoutlen` to no avail — ragtag’s mappings seem not to care about this setting.

How do I do it?

**Comment by tpope** [comment]
timeoutlen not ttimeoutlen

**Comment by tpope** [comment]
And set ttimeout if you haven't already.

**Comment by mrzool** [comment]
👍 thanks
