### ISSUE TITLE
vim-ragtag slows down :wq in terms of seconds

### ISSUE THREAD

**Issue by lorenzo-dev1** [tpope/vim-ragtag#58]
Hi, I started using vim-ragtag however as soon as I added it to my plugins I noticed that it slows down the :wq command in terms of seconds.

Not a big deal as I just load it when I need it, but are there some instructions executed when :wqing?

**Comment by tpope** [comment]
No, `:wq` shouldn't execute anything.

**Comment by lorenzo-dev1** [comment]
my Vim is still slow to close even after disabling vim-ragtag, so it is probably due to something else. Sorry for the useless issue.
